-- MySQL Script generated by MySQL Workbench
-- Fri Oct 28 23:54:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema physiodocs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `physiodocs` ;

-- -----------------------------------------------------
-- Schema physiodocs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `physiodocs` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `physiodocs` ;

-- -----------------------------------------------------
-- Table `department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `department` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `department` (
  `dept_id` INT NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(200) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `objective_assesments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objective_assesments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `objective_assesments` (
  `assessment_id` INT NOT NULL,
  `relevent_manual_muscle_testing` VARCHAR(1000) NULL,
  `relevent_soft_tissue_testing` VARCHAR(1000) NOT NULL,
  `total_assessment` VARCHAR(1000) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `patient_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patient_details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `patient_details` (
  `assessment_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `dept_id` INT NULL,
  `diagnosis` VARCHAR(100) NULL,
  `vitals_last_recorded` VARCHAR(100) NULL,
  `referring_physician` VARCHAR(100) NULL,
  `mode_of_payment` VARCHAR(100) NULL,
  `treating_therapist` INT NOT NULL,
  PRIMARY KEY (`assessment_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `plan_of_treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_of_treatment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `plan_of_treatment` (
  `assessment_id` INT NOT NULL,
  `long_term_goals` VARCHAR(1000) NULL,
  `short_term_goals` VARCHAR(1000) NOT NULL,
  `treatment_given` VARCHAR(1000) NOT NULL,
  `final_comments` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`assessment_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `assessment_id_UNIQUE` ON `plan_of_treatment` (`assessment_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `subjective_assessments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subjective_assessments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `subjective_assessments` (
  `assessment_id` INT NOT NULL,
  `medical_diagnosis` VARCHAR(1000) NOT NULL,
  `treating_diagnosis` VARCHAR(1000) NOT NULL,
  `subj_body_assmnt` LONGBLOB NOT NULL,
  `history_of_present_complaints` VARCHAR(1000) NOT NULL,
  `current_or_past_treatment` VARCHAR(1000) NULL,
  `medical_and_family_history` VARCHAR(1000) NULL,
  `surgical_history` VARCHAR(1000) NULL,
  `family_history` VARCHAR(1000) NULL,
  `social_history` VARCHAR(1000) NULL,
  `medications_and_allergies` VARCHAR(1000) NULL,
  `other_symptoms` VARCHAR(1000) NULL,
  PRIMARY KEY (`assessment_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_details` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(75) NULL,
  `middle_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(75) NULL,
  `date_of_birth` DATETIME NULL,
  `gender` CHAR(1) NULL COMMENT 'M, F, G, L, T',
  `nationality` VARCHAR(100) NULL,
  `preferred_language` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `phone` CHAR(10) NULL,
  `role` INT(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `user_details` (`email` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_roles` (
  `role_id` INT(4) NOT NULL AUTO_INCREMENT COMMENT 'PATIENT = 1,\n  DOCTOR = 2,\n  RECEPTIONIST = 3,\n  ADMIN = 4,\n  SUPER_ADMIN = 5',
  `role_name` VARCHAR(100) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `role_id_UNIQUE` ON `user_roles` (`role_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
